### ISSUE TITLE
Is the current code at master working correctly?

### ISSUE THREAD

**Issue by judavi** [grafeas/grafeas#381]
## Expected Behavior
Build an run the image using the Dockerfile on the root directory should start the Grafeas server correctly

## Actual Behavior
I'm building a new image using the Dockerfile. Then based on that new image I'm building https://github.com/grafeas/grafeas-pgsql/blob/master/server/Dockerfile. The build is succesfull but when I try to run the server I'm getting:

```bash
{"error":"all SubConns are in TransientFailure, latest connection error: timed out waiting for server handshake","message":"all SubConns are in TransientFailure, latest connection error: timed out waiting for server handshake","code":14,"details":[]}
```

As an alternative, I also tried running the main.go from v1beta1 and I added some debug flags:
```bash
GRPC_GO_LOG_VERBOSITY_LEVEL=99 GRPC_GO_LOG_SEVERITY_LEVEL=info GRPC_VERBOSITY=DEBUG go run main.go --config config.yaml
2019/09/16 20:00:16 pagination key is empty, generating...
2019/09/16 20:00:16 starting grpc server on 0.0.0.0:8080
INFO: 2019/09/16 20:00:16 parsed scheme: ""
INFO: 2019/09/16 20:00:16 scheme "" not registered, fallback to default scheme
INFO: 2019/09/16 20:00:16 ccResolverWrapper: sending update to cc: {[{[::]:8080 0  <nil>}] <nil>}
INFO: 2019/09/16 20:00:16 ClientConn switching balancer to "pick_first"
2019/09/16 20:00:16 grpc server is configured without client certificate authentication
INFO: 2019/09/16 20:00:16 pickfirstBalancer: HandleSubConnStateChange: 0xc00006c070, CONNECTING
INFO: 2019/09/16 20:00:36 transport: loopyWriter.run returning. connection error: desc = "transport is closing"
WARNING: 2019/09/16 20:00:36 grpc: addrConn.createTransport failed to connect to {[::]:8080 0  <nil>}: didn't receive server preface in time. Reconnecting...
INFO: 2019/09/16 20:00:36 pickfirstBalancer: HandleSubConnStateChange: 0xc00006c070, TRANSIENT_FAILURE
INFO: 2019/09/16 20:00:37 pickfirstBalancer: HandleSubConnStateChange: 0xc00006c070, CONNECTING
INFO: 2019/09/16 20:00:57 transport: loopyWriter.run returning. connection error: desc = "transport is closing"
WARNING: 2019/09/16 20:00:57 grpc: addrConn.createTransport failed to connect to {[::]:8080 0  <nil>}: didn't receive server preface in time. Reconnecting...
INFO: 2019/09/16 20:00:57 pickfirstBalancer: HandleSubConnStateChange: 0xc00006c070, TRANSIENT_FAILURE
INFO: 2019/09/16 20:00:58 pickfirstBalancer: HandleSubConnStateChange: 0xc00006c070, CONNECTING
^Csignal: interrupt
```

## Steps to Reproduce the Problem

Environment, commands

1.  Download the latest version of the code
2.  make 
3.  GRPC_GO_LOG_VERBOSITY_LEVEL=99 GRPC_GO_LOG_SEVERITY_LEVEL=info GRPC_VERBOSITY=DEBUG go run main.go --config config.yaml
4.  Go to http://localhost:8080/v1beta1/projects/user

## Additional info

config.yaml
```yaml
grafeas:
  # Grafeas api server config
  api:
    # Endpoint address
    address: "0.0.0.0:8080"
    # PKI configuration (optional)
    cafile:
    keyfile:
    certfile:
    # CORS configuration (optional)
    cors_allowed_origins:
      # - "http://example.net"
  storage_type: "postgres"
  # Postgres options
  postgres:
    # Database host
    host: "192.168.0.15:5432"
    # Database name
    dbname: "postgres"
    # Database username
    user: "postgres"
    # Database password
    password: "password"
    # Valid sslmodes disable, allow, prefer, require, verify-ca, verify-full.
    # See https://www.postgresql.org/docs/current/static/libpq-connect.html for details
    sslmode: "disable"
    # 32-bit URL-safe base64 key used to encrypt pagination tokens
    # If one is not provided, it will be generated.
    # Multiple grafeas instances in the same cluster need the same value.
    paginationkey:

```

**Comment by aysylu** [comment]
Hi @judavi, did you follow the steps described in [Starting Grafeas](https://github.com/grafeas/grafeas/blob/master/docs/running_grafeas.md#start-grafeas)? It sounds like you're trying to start the server from `grafeas-pgsql` Dockerfile, but also perhaps using the Dockerfile in `grafeas` GH project -- could you please clarify?

I was able to start the server in `go/v1beta1` per instructions. From the description of the issue, it sounds like you're trying to bring up the Grafeas server with PostgreSQL backend. I recommend using https://github.com/grafeas/grafeas-pgsql to get started with that.

**Comment by judavi** [comment]
Hi @aysylu 
Yes, in the past I was able to start the project successfully. I have been working to complete the PR from here https://github.com/grafeas/grafeas-pgsql/pull/6

I also tried the following :
```
cd ~/go/src/github.com/grafeas/grafeas
cd go/v1beta1
go run main/main.go
```
Output
````
➜  main git:(master) ✗ go run main.go
2019/09/16 20:43:56 starting grpc server on 0.0.0.0:8080
INFO: 2019/09/16 20:43:56 parsed scheme: ""
INFO: 2019/09/16 20:43:56 scheme "" not registered, fallback to default scheme
INFO: 2019/09/16 20:43:56 ccResolverWrapper: sending update to cc: {[{[::]:8080 0  <nil>}] <nil>}
INFO: 2019/09/16 20:43:56 ClientConn switching balancer to "pick_first"
2019/09/16 20:43:56 grpc server is configured without client certificate authentication
INFO: 2019/09/16 20:43:56 pickfirstBalancer: HandleSubConnStateChange: 0xc000032030, CONNECTING
WARNING: 2019/09/16 20:44:16 grpc: addrConn.createTransport failed to connect to {[::]:8080 0  <nil>}: didn't receive server preface in time. Reconnecting...
INFO: 2019/09/16 20:44:16 pickfirstBalancer: HandleSubConnStateChange: 0xc000032030, TRANSIENT_FAILURE
INFO: 2019/09/16 20:44:16 transport: loopyWriter.run returning. connection error: desc = "transport is closing"
INFO: 2019/09/16 20:44:17 pickfirstBalancer: HandleSubConnStateChange: 0xc000032030, CONNECTING
```

**Comment by judavi** [comment]
Basically what happened is I was testing my changes to remove the pgsql storage files from the main project. So I pulled the latest changes from the main repo (grafeas) and I faced the error. Then thinking it was something with my code I came back to the master branch and I tried to build the app without any of my changes but similar situation.

**Comment by aysylu** [comment]
Hm, interesting. I just synced to the latest and ran `go run main/main.go` in the same directory as you and got:

```
2019/09/16 15:53:36 starting grpc server on 0.0.0.0:8080
2019/09/16 15:53:36 grpc server is configured without client certificate authentication
```

Could you please confirm your `grafeas` GH repo is synced to the latest commit?

Also, I just merged https://github.com/grafeas/grafeas-pgsql/pull/7 which should fix one of the issues.

**Comment by judavi** [comment]
@aysylu yes the server is starting correctly. The extra information is because I'm using 
```
GRPC_GO_LOG_VERBOSITY_LEVEL=99 GRPC_GO_LOG_SEVERITY_LEVEL=info GRPC_VERBOSITY=DEBUG
```
Then the error is happening when you try to use one of the methods of the API.  Like
```
http://localhost:8080/v1beta1/projects/user --> this normally should reply with a Json

**Comment by judavi** [comment]
Just to be sure it wasn't something with my local repo I started a new container and I pulled the code there and manually build and started the API: https://asciinema.org/a/nP4XRtzynBvONDT60Rx0oNXz7

**Comment by aysylu** [comment]
Great! So is this resolved now?

**Comment by aysylu** [comment]
@judavi please re-open if this is still an issue. Closing for now.

**Comment by judavi** [comment]
@aysylu I'm afraid this is still happening. Is not only about starting the server, because the server is "starting" correctly. The issue appears as soon as you try to use any of the services of the API. Something like http://localhost:8080/v1beta1/projects

**Comment by judavi** [comment]
cc @vtsao

**Comment by judavi** [comment]
Hi @aysylu  curl or the browser, same result:
```
~ curl http://localhost:8080/v1beta1/projects
{"error":"all SubConns are in TransientFailure, latest connection error: timed out waiting for server handshake","message":"all SubConns are in TransientFailure, latest connection error: timed out waiting for server handshake","code":14,"details":[]}%
```

**Comment by judavi** [comment]
On the server side, if you enable GRPC debug information this is the output:
```
$ export GRPC_GO_LOG_VERBOSITY_LEVEL=99 
$ export GRPC_GO_LOG_SEVERITY_LEVEL=info 
$ export GRPC_VERBOSITY=DEBUG
$ go run main.go --config config.yaml
2019/10/08 17:26:18 starting grpc server on localhost:8080
INFO: 2019/10/08 17:26:18 parsed scheme: ""
INFO: 2019/10/08 17:26:18 scheme "" not registered, fallback to default scheme
INFO: 2019/10/08 17:26:18 ccResolverWrapper: sending update to cc: {[{127.0.0.1:8080 0  <nil>}] <nil>}
INFO: 2019/10/08 17:26:18 ClientConn switching balancer to "pick_first"
2019/10/08 17:26:18 grpc server is configured without client certificate authentication
INFO: 2019/10/08 17:26:18 pickfirstBalancer: HandleSubConnStateChange: 0xc0001e0940, CONNECTING
WARNING: 2019/10/08 17:26:38 grpc: addrConn.createTransport failed to connect to {127.0.0.1:8080 0  <nil>}: didn't receive server preface in time. Reconnecting...
INFO: 2019/10/08 17:26:38 transport: loopyWriter.run returning. connection error: desc = "transport is closing"
INFO: 2019/10/08 17:26:38 pickfirstBalancer: HandleSubConnStateChange: 0xc0001e0940, TRANSIENT_FAILURE
INFO: 2019/10/08 17:26:39 pickfirstBalancer: HandleSubConnStateChange: 0xc0001e0940, CONNECTING
INFO: 2019/10/08 17:26:59 transport: loopyWriter.run returning. connection error: desc = "transport is closing"
WARNING: 2019/10/08 17:26:59 grpc: addrConn.createTransport failed to connect to {127.0.0.1:8080 0  <nil>}: didn't receive server preface in time. Reconnecting...
INFO: 2019/10/08 17:26:59 pickfirstBalancer: HandleSubConnStateChange: 0xc0001e0940, TRANSIENT_FAILURE
INFO: 2019/10/08 17:27:00 pickfirstBalancer: HandleSubConnStateChange: 0xc0001e0940, CONNECTING
INFO: 2019/10/08 17:27:20 transport: loopyWriter.run returning. connection error: desc = "transport is closing"
WARNING: 2019/10/08 17:27:20 grpc: addrConn.createTransport failed to connect to {127.0.0.1:8080 0  <nil>}: didn't receive server preface in time. Reconnecting...
INFO: 2019/10/08 17:27:20 pickfirstBalancer: HandleSubConnStateChange: 0xc0001e0940, TRANSIENT_FAILURE
INFO: 2019/10/08 17:27:23 pickfirstBalancer: HandleSubConnStateChange: 0xc0001e0940, CONNECTING
WARNING: 2019/10/08 17:27:43 grpc: addrConn.createTransport failed to connect to {127.0.0.1:8080 0  <nil>}: didn't receive server preface in time. Reconnecting...
```

**Comment by judavi** [comment]
Hi @aysylu @vtsao I built again on a clean machine (Centos 7.5). Similar situation. This time I'm running the DB on the host to discard issues with Postgres running on a container. Same result. I'm not able to use any of the endpoints using CURL or the browser.
A complete log of the build and run command is available here: https://gist.github.com/judavi/bb8d6eb20fcce037dbbf4d02545daad6

Please, could you give me some advice, for building I'm not using anything different to "make" and then go run main.go --config config.yaml

**Comment by judavi** [comment]
@aysylu @vtsao 
Ok, I have some extra information. If I go back to an old version the REST API starts working again.  For example:
```
main git:(master) ✗ git checkout 9e63ccc6d9ce929f7674fe7ad693b10832760af7
Note: checking out '9e63ccc6d9ce929f7674fe7ad693b10832760af7'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 9e63ccc... Merge pull request #361 from aysylu/0.1.0
````
Then
```
make
...removed make output...

go run main.go --config config.yaml
2019/10/10 15:00:07 pagination key is empty, generating...
2019/10/10 15:00:07 starting grpc server on localhost:8080
2019/10/10 15:00:07 grpc server is configured without client certificate authentication
```
and finally
```
curl http://localhost:8080/v1beta1/projects
{"projects":[],"nextPageToken":""}%     
```
